name: Django Development

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Generate .env file
      run: |
        echo "DEBUG=True" > .env
        echo "SECRET_KEY='6m9cudma*vj!@(y2*nc45az*x*6cjdcjr4@_osfuw^yt(lpux$'" >> .env
        echo "DATABASE_NAME=django_db" >> .env
        echo "DATABASE_USER=POSTGRES_USER=root" >> .env
        echo "DATABASE_PASSWORD=secure_password" >> .env
        echo "DATABASE_HOST=localhost" >> .env
        echo "DATABASE_PORT=5432" >> .env

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 1
        done

    - name: Check Folder List
      run: |
        echo "Current directory contents:"
        ls -la
        cat .env

    - name: Set up database
      run: |
        echo "Setting up the database..."
        # Add any necessary database setup commands here

    - name: Run migrations
      run: |
        python django_project/manage.py migrate

    - name: Run tests
      run: |
        python django_project/manage.py test
