name: Django Development

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data

    steps:
    - uses: actions/checkout@v2

    - name: Check secrets
      run: |
        echo "POSTGRES_DB: ${{ secrets.POSTGRES_DB }}"
        echo "POSTGRES_USER: ${{ secrets.POSTGRES_USER }}"
        echo "POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}"
        echo "DATABASE_URL: ${{ secrets.DATABASE_URL }}"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python3 django_project/manage.py test
